# -*- coding: utf-8 -*-
"""Best 100 movies to watch

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ri2eRtHZdebEHnCzIsR_UHVpIUd1J3cD
"""

import requests

from bs4 import BeautifulSoup

url = "https://web.archive.org/web/20200518073855/https://www.empireonline.com/movies/features/best-movies-2/"

response = requests.get(url)

website_html = response.text

soup = BeautifulSoup(website_html,'html.parser')

all_movies = soup.find_all(name ='h3',class_= 'title')

print(all_movies)

movies_titles = [movie.getText() for movie in all_movies]

print(movies_titles)

movies_titles = movies_titles[::-1]

movies_titles

with open('movies_titles.text',mode='w') as file:
  for movie in movies_titles:
    file.write(f"{movie}\n")